// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AutomationTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinWindow uIExpressGoogleChromeWindow1 = this.UIExpressGoogleChromeWindow.UIExpressGoogleChromeWindow1;
            #endregion

            // Click 'Express - Google Chrome' window
            Mouse.Click(uIExpressGoogleChromeWindow1, new Point(876, 440));
        }
        
        #region Properties
        public UIExpressGoogleChromeWindow UIExpressGoogleChromeWindow
        {
            get
            {
                if ((this.mUIExpressGoogleChromeWindow == null))
                {
                    this.mUIExpressGoogleChromeWindow = new UIExpressGoogleChromeWindow();
                }
                return this.mUIExpressGoogleChromeWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIExpressGoogleChromeWindow mUIExpressGoogleChromeWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIExpressGoogleChromeWindow : WinWindow
    {
        
        public UIExpressGoogleChromeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Express - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Express - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UIExpressGoogleChromeWindow1
        {
            get
            {
                if ((this.mUIExpressGoogleChromeWindow1 == null))
                {
                    this.mUIExpressGoogleChromeWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUIExpressGoogleChromeWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Express";
                    this.mUIExpressGoogleChromeWindow1.WindowTitles.Add("Express - Google Chrome");
                    #endregion
                }
                return this.mUIExpressGoogleChromeWindow1;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIExpressGoogleChromeWindow1;
        #endregion
    }
}
